---
# For state=absent:
- block:
    - name: Remove locust.io installation
      file:
        path: '{{ install_path }}/locust.io'
        state: absent
    - meta: end_play
  when: state == 'absent'

# For state=stopped:
- block:
    - name: Stop locust.io
      command: pkill -f '{{ install_path }}/locust.io/virtenv/bin/locust'
      register: procs_killed
      changed_when: procs_killed.rc == 0
      failed_when: procs_killed.rc > 1
    - meta: end_play
  when: state == 'stopped'

# For all other states, make sure Locust.io is installed
- name: Add ZeroMQ repository
  yum_repository:
    baseurl: 'https://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-draft/CentOS_7/'
    gpgkey: 'http://download.opensuse.org/repositories/network:/messaging:/zeromq:/release-draft/CentOS_7/repodata/repomd.xml.key'
    enabled: true
    name: 'ZeroMQ'
    description: 'Upstream repository for ZeroMQ message queue'
    state: present
- name: Update repo caches
  yum:
    name: python-virtualenv
    update_cache: true
- name: Install required packages
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - zeromq-devel
    - gcc
- name: Check installation directory
  file:
    path: '{{ install_path }}/locust.io'
    state: directory
    mode: 0700
- name: Install python requirements
  pip:
    name: 'locustio'
    virtualenv: '{{ install_path }}/locust.io/virtenv'

# For state=present:
- name: Locust.IO installation done.
  meta: end_play
  when: state == 'present'

# For state=restarted:
- name: Stop locust.io
  command: pkill locust
  changed_when: procs_killed.rc == 0
  failed_when: procs_killed.rc > 1
  when: state == 'restarted'

# For state=started and state=restarted:
- name: Look for running locust.io processes
  command: pgrep -f '{{ install_path }}/locust.io/virtenv/bin/locust'
  register: pgrep_out
  changed_when: false
  failed_when: pgrep_out.rc > 1
- name: Start locust.io
  command: |
    bash -c 'nohup {{ install_path }}/locust.io/virtenv/bin/locust
    --slave
    --master-host={{ master_host }}
    --master-port={{ master_port }}
    -f {{ locustfile }} &'
  when: pgrep_out.rc == 1
