---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: De-install instance locust-1
      include_role:
        name: tinx.locust_slave
      vars:
        instance_name: locust-1
        state: absent
    - name: Stop instance locust-2
      include_role:
        name: tinx.locust_slave
      vars:
        instance_name: locust-2
        state: stopped
    - name: Install instance 'slave'
      include_role:
        name: tinx.locust_slave
      vars:
        master_host: master
        instance_data: data/
        locustfile: locustfile.py
    - name: Start instance locust-5
      include_role:
        name: tinx.locust_slave
      vars:
        instance_name: locust-5
        instance_data: data/
        master_host: master
        locustfile: /opt/locust.io/locust-5/./locustfile.py
        state: started
